Website = "https://minitechnicus.org/"

[Details]
  Icon = "logo.png"
  Name = "MT Admin"
  ID = "com.admin.minitechnicus.app"
  Version = "1.0.0"
  Build = 2

[LinuxAndBSD]
  GenericName = "MT Admin"
  Categories = ["Admin"]
  Keywords = ["MT", "MiniTechnicus", "Admin"]
